Comp7071-A2/Areas/Housing/Models/ApplicationReference.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Comp7071_A2.Areas.Housing.Models
{
    public class ApplicationReference
    {
        [Key]
        public Guid ID { get; set; }

        [Required]
        [ForeignKey("Application")]
        public Guid ApplicationID { get; set; }

        [Required]
        [ForeignKey("Contact")]
        public Guid ContactID { get; set; }

        public virtual Application Application { get; set; }
        public virtual Contact Contact { get; set; }
    }
}

Comp7071-A2/Areas/Housing/Controllers/ApplicationReferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Comp7071_A2.Areas.Housing.Models;
using Comp7071_A2.Data;

namespace Comp7071_A2.Areas.Housing.Controllers
{
    [Area("Housing")]
    public class ApplicationReferencesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationReferencesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Housing/ApplicationReferences
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ApplicationReferences.Include(a => a.Application).Include(a => a.Contact);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Housing/ApplicationReferences/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationReference = await _context.ApplicationReferences
                .Include(a => a.Application)
                .Include(a => a.Contact)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (applicationReference == null)
            {
                return NotFound();
            }

            return View(applicationReference);
        }

        // GET: Housing/ApplicationReferences/Create
        public IActionResult Create()
        {
            ViewData["ApplicationID"] = new SelectList(_context.Applications, "ID", "RenterID");
            ViewData["ContactID"] = new SelectList(_context.Contacts, "ID", "Email");
            return View();
        }

        // POST: Housing/ApplicationReferences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ApplicationID,ContactID")] ApplicationReference applicationReference)
        {
            if (ModelState.IsValid)
            {
                applicationReference.ID = Guid.NewGuid();
                _context.Add(applicationReference);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationID"] = new SelectList(_context.Applications, "ID", "RenterID", applicationReference.ApplicationID);
            ViewData["ContactID"] = new SelectList(_context.Contacts, "ID", "Email", applicationReference.ContactID);
            return View(applicationReference);
        }

        // GET: Housing/ApplicationReferences/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationReference = await _context.ApplicationReferences.FindAsync(id);
            if (applicationReference == null)
            {
                return NotFound();
            }
            ViewData["ApplicationID"] = new SelectList(_context.Applications, "ID", "RenterID", applicationReference.ApplicationID);
            ViewData["ContactID"] = new SelectList(_context.Contacts, "ID", "Email", applicationReference.ContactID);
            return View(applicationReference);
        }

        // POST: Housing/ApplicationReferences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,ApplicationID,ContactID")] ApplicationReference applicationReference)
        {
            if (id != applicationReference.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicationReference);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationReferenceExists(applicationReference.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationID"] = new SelectList(_context.Applications, "ID", "RenterID", applicationReference.ApplicationID);
            ViewData["ContactID"] = new SelectList(_context.Contacts, "ID", "Email", applicationReference.ContactID);
            return View(applicationReference);
        }

        // GET: Housing/ApplicationReferences/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationReference = await _context.ApplicationReferences
                .Include(a => a.Application)
                .Include(a => a.Contact)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (applicationReference == null)
            {
                return NotFound();
            }

            return View(applicationReference);
        }

        // POST: Housing/ApplicationReferences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var applicationReference = await _context.ApplicationReferences.FindAsync(id);
            if (applicationReference != null)
            {
                _context.ApplicationReferences.Remove(applicationReference);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationReferenceExists(Guid id)
        {
            return _context.ApplicationReferences.Any(e => e.ID == id);
        }
    }
}

Comp7071-A2/Areas/Housing/Views/ApplicationReferences/Create.cshtml
@model Comp7071_A2.Areas.Housing.Models.ApplicationReference

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ApplicationReference</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApplicationID" class="control-label"></label>
                <select asp-for="ApplicationID" class ="form-control" asp-items="ViewBag.ApplicationID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ContactID" class="control-label"></label>
                <select asp-for="ContactID" class ="form-control" asp-items="ViewBag.ContactID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comp7071-A2/Areas/Housing/Views/ApplicationReferences/Delete.cshtml
@model Comp7071_A2.Areas.Housing.Models.ApplicationReference

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationReference</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Application.RenterID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact.Email)
        </dd>
    </dl>
    
    <form asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Index">Back to List</a>
    </form>
</div>

Comp7071-A2/Areas/Housing/Views/ApplicationReferences/Details.cshtml
@model Comp7071_A2.Areas.Housing.Models.ApplicationReference

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ApplicationReference</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Application.RenterID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Index">Back to List</a>
</div>

Comp7071-A2/Areas/Housing/Views/ApplicationReferences/Edit.cshtml
@model Comp7071_A2.Areas.Housing.Models.ApplicationReference

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ApplicationReference</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ApplicationID" class="control-label"></label>
                <select asp-for="ApplicationID" class="form-control" asp-items="ViewBag.ApplicationID"></select>
                <span asp-validation-for="ApplicationID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactID" class="control-label"></label>
                <select asp-for="ContactID" class="form-control" asp-items="ViewBag.ContactID"></select>
                <span asp-validation-for="ContactID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comp7071-A2/Areas/Housing/Views/ApplicationReferences/Index.cshtml
@model IEnumerable<Comp7071_A2.Areas.Housing.Models.ApplicationReference>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Application)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Application.RenterID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact.Email)
            </td>
            <td>
                <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-area="Housing" asp-controller="ApplicationReferences" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>